# Generated by Django 5.2.4 on 2025-07-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_bb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
    ]
